// Generated by Lekko. DO NOT EDIT.
package lekkodefault

import (
	"context"

	client "github.com/lekkodev/go-sdk/client"
)

type LekkoClient struct {
	client.Client
}

// Controls behavior for access to a protected endpoint
func (c *LekkoClient) GetCanAccess(endpoint string, isUserAdmin bool) bool {
	ctx := context.Background()
	ctx = client.Add(ctx, "endpoint", endpoint)
	ctx = client.Add(ctx, "is_user_admin", isUserAdmin)
	result, err := c.GetBool(ctx, "default", "can-access")
	if err == nil {
		return result
	}
	return getCanAccess(endpoint, isUserAdmin)
}
